// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDvfJxGeaMvBshw3iQHfQEI2MF_YOljAw',
    appId: '1:858209307894:web:f25615ed38fe53f8cb70d7',
    messagingSenderId: '858209307894',
    projectId: 'instaclone-kuchi',
    authDomain: 'instaclone-kuchi.firebaseapp.com',
    storageBucket: 'instaclone-kuchi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdODwZqPH9eutvjSOKW_8vVrIXhbfvObM',
    appId: '1:858209307894:android:81ad461a0d691904cb70d7',
    messagingSenderId: '858209307894',
    projectId: 'instaclone-kuchi',
    storageBucket: 'instaclone-kuchi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYGwzR-RGL-ARZBXD7X-Frc5VXEUGFvU',
    appId: '1:858209307894:ios:ad2918f1ce6ce782cb70d7',
    messagingSenderId: '858209307894',
    projectId: 'instaclone-kuchi',
    storageBucket: 'instaclone-kuchi.appspot.com',
    iosClientId: '858209307894-68l4ea5hff7hc1u9mi6fhlpiqcdbgf6r.apps.googleusercontent.com',
    iosBundleId: 'com.mudit.instaclone',
  );
}
